default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_proj_development
  username: <%= ENV["RAILS_PROJ_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["RAILS_PROJ_DEV_DATABASE_PASSWORD"] %>

test:
  <<: *default
  database: rails_proj_test
  username: <%= ENV["RAILS_PROJ_DEV_DATABASE_USERNAME"] %>
  password: <%= ENV["RAILS_PROJ_DEV_DATABASE_PASSWORD"] %>

production:
  <<: *default
  database: rails_proj_production
  username: rails_proj
  password: <%= ENV["RAILS_PROJ_DATABASE_PASSWORD"] %>
